config/routes.rb
Rails.application.routes.draw do

get 'challenges/:challenge_id/dares/:id/:token' => 'dares#show_invitation_dare', as: 'invitation_dare'

devise_scope :user do
  get "/users/sign_up/:token" => "devise/registrations#new", as: 'invitation_register'
end

resources :invitations, only: [:create, :new]

  resources :challenges do
    resources :dares do
      member do
        put 'accept_challenge'
        put 'reject_challenge'
      end
      resources :votes
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations"}

  get 'users/search' => 'users#search'
  get 'users/autocomplete' => 'users#autocomplete'
  get 'users/:id' => 'users#show', as: 'user'
  get 'users' => 'users#index', as: 'users'
  get 'dares_voting' => 'dares#show_voting', as: 'dares_voting'
  get 'notifications' => 'notifications#index'
  put 'challenges/:challenge_id/dares/:id/delete_proof/:proof_type/:proof_id' => 'dares#delete_proof', as: 'delete_proof'
  put 'challenges/:challenge_id/dares/:id/accept_proof' =>  'dares#accept_proof', as: 'accept_proof'
  put 'challenges/:challenge_id/dares/:id/reject_proof' =>  'dares#reject_proof', as: 'reject_proof'
  

  get '/' => 'challenges#intro', as: 'intro'
  root 'challenges#intro'

end

app/models/dare.rb
class Dare < ActiveRecord::Base

  belongs_to :challenge, counter_cache: true
  belongs_to :acceptor, class_name: "User"
  belongs_to :challenger, class_name: "User"
  belongs_to :invitation

  has_many :votes


  before_save :change_status
  before_save :create_start_date
  before_save :set_proof_array

  # validate :cannot_challenge_if_acceptor_already_accepted

  def process
    self.no_proof_fail?
    self.success_unvalidated?
    self.up_for_voting? 
    self.voting_finished? 
    self.dare_expires_tommorow?
  end

  def post_on_fb(event)
    acceptor = self.acceptor
    challenger = self.challenger
    challenge = self.challenge
    url = Rails.application.routes.url_helpers.challenge_dare_url(self.challenge_id, self.id, :host => "simon-challenger.herokuapp.com")
    if acceptor.can_post_on_fb?
      case event
      when "accepted_challenge"
        attachment = {"name"=>"#{challenge.name}", "link"=> url, "description"=>"Follow #{acceptor.username}'s progress here!"}
        acceptor.facebook.put_wall_post("I accepted the #{challenge.name} challenge from the Challenger!", attachment) 
      when "uploaded_proof"
        attachment = {"name"=>"#{challenge.name}", "link"=> url, "description"=>"Check it out here!"}
        acceptor.facebook.put_wall_post("I uploaded proof of completion of the #{challenge.name} challenge!", attachment) 
      when "Voting started"
        attachment = {"name"=>"#{challenge.name}", "link"=> url, "description"=>"Check it out here!"}
        acceptor.facebook.put_wall_post("My #{challenge.name} challenge was put to the vote!", attachment) 
      when "Voting finished"
        attachment = {"name"=>"#{challenge.name}", "link"=> url, "description"=>"See if I won here!"}
        acceptor.facebook.put_wall_post("My #{challenge.name} challenge's voting has finished!", attachment) 
      end
    end

    if  challenger.can_post_on_fb? && event == "accepted_challenge" && challenger.id != acceptor.id
      attachment = {"name"=>"#{challenge.name}", "link"=> url, "description"=>"Follow #{challenger.username}'s challenge here!"}
      challenger.facebook.put_wall_post("I challenged #{acceptor.username} to the #{challenge.name} on Challenger!", attachment) 
    end
  end

  def dare_expires_tommorow?
    if self.start_date.midnight <= 6.days.ago 
      UserMailer.dare_expires_tommorrow(self).deliver
    end
  end

  def is_invitation?
    self.status = 'invitation-pending'
  end

  def cannot_challenge_if_acceptor_already_accepted
    if self.acceptor.my_accepted_challenges.where("challenge_id = ?", self.challenge_id).any?
      errors.add(:acceptor_id, 'That user already accepted that challenge!')
    end
  end

  def is_self_selected?
    self.acceptor_id == self.challenger_id
  end

  def self.newest_voting
    where(status: 'Voting').order("voting_start_date desc")
  end

  def resolved?
    self.status == "Success" || self.status == "Failed"
  end

  def set_proof_array
    if self.utube_link.nil?
      self.utube_link = []
      save!
    end
  end

  def create_start_date
    if status == 'Accepted' && start_date.blank?
      self.start_date = DateTime.now
    end
  end

  def unaccepted_this_dare?
    if self.acceptor.accepted_dares && self.acceptor.accepted_dares.map{|e| e.challenge_id}.include?(self.challenge_id)
      errors.add :base, 'Already accepted'
      false
    end
  end

  def finishing_in
    (((self.start_date.midnight + 7.days) - Time.now)/86400).floor
  end

  def change_status
    if status.blank?
      if self.acceptor_id == self.challenger_id
        self.status = "Accepted"
      else
        self.status = "Pending"
      end
    end
  end



  def rejected?
    self.status == "Rejected"
  end

  def times_up?
    self.start_date.midnight <= 7.days.ago if self.start_date?
  end

  def still_have_time?
    self.start_date.midnight > 7.days.ago if self.start_date?
  end

  def unresolved?
    self.status == "Pending" || self.status == "Accepted"
  end

  def no_proof_fail?
    if self.utube_link.blank? && self.times_up? && self.unresolved?
      self.status = 'Failed'
      save!
      UserMailer.challenger_no_proof_fail(self.challenger, self.acceptor, self).deliver
      UserMailer.acceptor_no_proof_fail(self.challenger, self.acceptor, self).deliver
    end
  end

  def proof_not_validated?
    self.proof_status != "Proof Accepted" && self.proof_status != "Proof Rejected"
  end

  def time_for_proof_validation_ended?
    if self.start_date?
      self.start_date.midnight <= 9.days.ago 
    end
  end

  def success_unvalidated?
    if self.proof? && self.time_for_proof_validation_ended? && self.proof_not_validated?
      self.status = 'Success'
      save!
    end
  end




  def votes_for
    self.votes.where("vote_for = ?", true).count
  end

  def votes_against
    self.votes.where("vote_for = ?", false).count
  end 

  def won_voting?
    self.votes_for >= self.votes_against
  end

  def voting_end_date
    self.voting_start_date.midnight + 5.days if self.voting_start_date?
  end

  def voting_finished?
    unless self.after_voting? || self.voting_start_date.nil?
      if self.voting_end_date <= DateTime.now
        if self.won_voting?
          self.status = 'Success'
          self.voting_status = 'Success'
        else
          self.status = 'Failed'
          self.voting_status = 'Failed'
        end
        save!
        self.post_on_fb("Voting finished")
        if self.is_self_selected?
          UserMailer.self_selected_voting_ended(self.challenger, self).deliver
        else
          UserMailer.challenger_voting_ended(self.challenger, self.acceptor, self).deliver
          UserMailer.acceptor_voting_ended(self.challenger, self.acceptor, self).deliver
        end
      else
        false
      end
    end

  end

  def after_voting?
    self.voting_status == 'Success' || self.voting_status == 'Failed'
  end

  def voting_in_progress?
    self.status == 'Voting'
  end


  def proof?
    self.utube_link? || self.pic_link?
  end

  def up_for_voting?
    if self.times_up? && self.unresolved? && self.proof? && self.status != 'Voting'
      self.voting_start_date = DateTime.now
      self.status = 'Voting'
      save!
      self.post_on_fb("Voting started")
      UserMailer.voting_started(self.challenger, self.acceptor, self).deliver
    end
  end

end

app/controllers/dares_controller.rb
class DaresController < ApplicationController
  before_action :set_dare, except: [:index, :new, :create, :show_voting, :show_invitation_dare]
  before_action :authenticate_user!, except: :show_invitation_dare
  before_action :set_challenger_acceptor, only: [:create]  

  def show_invitation_dare
      @invitation = Invitation.where("token = ?", params[:token]).first
      @dare = Dare.where("invitation_id = ?", @invitation.id).first
    if @dare.status != 'Invitation-pending'
      redirect_to challenge_dare_path(@dare.challenge_id, @dare.id), notice: 'This invitation has already been processed'
    end
  end

  def show_voting
    @dares_voting = Dare.where('status = ?', 'Voting')
  end

  def accept_challenge
    if @dare.status = 'Invitation-pending'
      @dare.acceptor_id = current_user.id
    end
    @dare.status = 'Accepted'
    @dare.start_date = DateTime.now
    if @dare.save
      UserMailer.user_accepted_challenge(@dare.challenger, @dare.acceptor, @dare).deliver
      UserMailer.you_accepted_challenge(@dare.challenger, @dare.acceptor, @dare).deliver
      @dare.post_on_fb("accepted_challenge")
      redirect_to challenge_dare_url(@dare.challenge_id, @dare.id), notice: 'You accepted the challenge!'
    else
      redirect_to challenge_dare_url(@dare.challenge_id, @dare.id), notice: 'Something went wrong!'
    end
  end

  def reject_challenge
    @dare.status = 'Rejected'
    @dare.end_date = DateTime.now
    if @dare.save
      UserMailer.user_rejected_challenge(@dare.challenger, @dare.acceptor, @dare).deliver
      UserMailer.you_rejected_challenge(@dare.challenger, @dare.acceptor, @dare).deliver
      redirect_to challenge_dare_url(@dare.challenge_id, @dare.id), alert: 'You rejected the challenge!'
    else
      redirect_to challenge_dare_url(@dare.challenge_id, @dare.id), notice: 'Something went wrong!'
    end
  end

  def accept_proof
    @dare.status = 'Success'
    @dare.proof_status = 'Accepted'
    if @dare.save
      UserMailer.challenger_accepted_proof(@dare.challenger, @dare.acceptor, @dare).deliver
      UserMailer.accepted_proof(@dare.challenger, @dare.acceptor, @dare).deliver
      redirect_to challenge_dare_url(@dare.challenge_id, @dare.id), notice: 'You accepted the proof!'
    else
      redirect_to challenge_dare_url(@dare.challenge_id, @dare.id), notice: 'Something went wrong!'
    end
  end

  def reject_proof
    @dare.status = 'Voting'
    @dare.proof_status = 'Rejected' unless @dare.is_self_selected?
    @dare.voting_start_date = DateTime.now
    if @dare.save
      if @dare.is_self_selected?
        UserMailer.self_selected_voting_started(@dare.challenger, @dare).deliver
        redirect_to challenge_dare_url(@dare.challenge_id, @dare.id), notice: 'You finished uploading proof!'
      else
        UserMailer.challenger_rejected_proof(@dare.challenger, @dare.acceptor, @dare).deliver
        UserMailer.rejected_proof(@dare.challenger, @dare.acceptor, @dare).deliver
        UserMailer.voting_started(@dare.challenger, @dare.acceptor, @dare).deliver
        redirect_to challenge_dare_url(@dare.challenge_id, @dare.id), notice: 'You rejected the proof!'
      end
    else
      redirect_to challenge_dare_url(@dare.challenge_id, @dare.id), notice: 'Something went wrong!'
    end
  end

  def delete_proof
    if params[:proof_type] == 'pic'
      @dare.pic_link.delete_at(params[:proof_id].to_i)
      @dare.pic_link_will_change!
    else
      @dare.utube_link.delete(params[:proof_id])
      @dare.utube_link_will_change!
    end
    if @dare.save
      redirect_to challenge_dare_url(@dare.challenge_id, @dare.id), notice: 'Proof deleted!'
    else
      redirect_to challenge_dare_url(@dare.challenge_id, @dare.id), notice: 'Something went wrong!'
    end
  end


  def show
    @vote = Vote.new
  end


  def create
    @challenge = Challenge.find(params[:challenge_id])
    @dare = Dare.new(dare_params)

    if @dare.save
      if params[:dare][:challenger_id] == params[:dare][:acceptor_id]
        UserMailer.self_challenge(@challenger, @dare).deliver
        @dare.post_on_fb("accepted_challenge")
        redirect_to challenge_dare_path(@challenge, @dare), notice: 'You accepted the challenge!'
      else
        UserMailer.you_challenged(@challenger, @acceptor, @dare).deliver
        UserMailer.you_were_challenged(@challenger, @acceptor, @dare).deliver
        redirect_to challenge_dare_path(@challenge, @dare), notice: "You challenged #{@acceptor.username} to #{@challenge.name}!"
      end
    else
      render :new
    end  
  end

  def new
    @dare = Dare.new
    @challenge = Challenge.find(params[:challenge_id])
    @invitation = Invitation.new
  end



  def update
    if @dare.update(dare_params)
      if params[:dare][:vid_link]
        if params[:dare][:vid_link].empty?
          redirect_to challenge_dare_path(params[:challenge_id], @dare), alert: 'Link to video not provided'
        else
          vid_link = YouTubeAddy.extract_video_id(params[:dare][:vid_link])
          if vid_link.length == 11
            @dare.utube_link = @dare.utube_link + [vid_link]
            @dare.save!
            @dare.post_on_fb("uploaded_proof")
            if @dare.is_self_selected?
              redirect_to challenge_dare_path(params[:challenge_id], @dare), notice: 'Added proof'
            else
              UserMailer.acceptor_uploaded_proof(@dare.challenger, @dare.acceptor, @dare).deliver
              redirect_to challenge_dare_path(params[:challenge_id], @dare), notice: 'Added proof'
            end
          else
            redirect_to challenge_dare_path(params[:challenge_id], @dare), alert: 'The link is not a valid Youtube link'
          end
        end
      elsif params[:dare][:pic_link]
        @dare.pic_link = @dare.pic_link + [params[:dare][:pic_link]]
        @dare.save!
        @dare.post_on_fb("uploaded_proof")
        redirect_to challenge_dare_path(params[:challenge_id], @dare), notice: 'Added proof'
      else
        redirect_to challenges_path, notice: 'Yay!'
      end
    else
      redirect_to root_path, notice: 'Something went wrong'
    end
  end

  def destroy
    @dare.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Dare was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

  def set_dare
    @dare = Dare.find(params[:id])
  end

  def set_challenger_acceptor   
    @challenger = User.find(params[:dare][:challenger_id])
    @acceptor = User.find(params[:dare][:acceptor_id])
  end

  def dare_params
    params.require(:dare).permit(:status, :amount, :acceptor_id, :challenger_id, :challenge_id, :utube_link, :start_date, :end_date, :with_bet, :vid_link, :pic_link)
  end

end

app/helpers/dares_helper.rb
module DaresHelper
end

app/views/dares/_display_proof.html.haml
- if @dare.utube_link?
  %h3
    Proof uploaded by #{@dare.acceptor.username}
    - @dare.utube_link.each_with_index do |vid, index|
      .embed-responsive.embed-responsive-16by9
        %iframe.embed-responsive-item{:src => "https://www.youtube.com/embed/#{vid}"}
      %br

      - if current_user.is_acceptor?(@dare) && @dare.status != 'Voting'
        = link_to 'Delete proof', delete_proof_path(@dare.challenge_id, @dare, 'vid', vid), method: :put
      - if current_user.is_challenger?(@dare) && @dare.proof_not_validated? && @dare.unresolved? && @dare.acceptor_id != @dare.challenger_id
        = link_to 'Accept proof', accept_proof_path(@dare.challenge_id, @dare.id), method: :put
        = link_to 'Reject proof', reject_proof_path(@dare.challenge_id, @dare.id), method: :put
  
- if @dare.pic_link?
  - @dare.pic_link.each_with_index do |pic, index|
    = link_to (image_tag pic, class: 'img-responsive'), pic
    - if current_user.is_acceptor?(@dare) && @dare.status != 'Voting'
      = link_to 'Delete proof', delete_proof_path(@dare.challenge_id, @dare, 'pic', index), method: :put
    - if current_user.is_challenger?(@dare) && @dare.proof_not_validated? && @dare.unresolved? && @dare.acceptor_id != @dare.challenger_id
      = link_to 'Accept proof', accept_proof_path(@dare.challenge_id, @dare.id), method: :put
      = link_to 'Reject proof', reject_proof_path(@dare.challenge_id, @dare.id), method: :put

app/views/dares/_error.html.haml
%h4
  = "#{pluralize(@dare.errors.count, "error")} prohibited this dare from being saved:"
  %ul
    - @dare.errors.full_messages.each do |msg|
      %li= msg

app/views/dares/_upload_proof.html.haml
= form_for([@dare.challenge, @dare]) do |f|
  = f.label :vid_link
  = f.text_field :vid_link
  = f.submit "Upload Youtube Video", class: "btn btn-success"

= form_for([@dare.challenge, @dare]) do |f|
  = f.label :pic_link, value: 'Image link'
  = f.text_field :pic_link, value: ''
  = f.submit "Upload Image", class: "btn btn-success"

- if @dare.utube_link.any? || @dare.pic_link.any?
  = link_to "Finished uploading proof", reject_proof_path(@dare.challenge_id, @dare.id), method: :put

app/views/dares/_voting.html.haml
%h3
	Votes:

%h4
	For: #{@dare.votes_for}
%h4	
	Against: #{@dare.votes_against}
%h4
	Voting ends on: #{@dare.voting_end_date}

-if user_signed_in?
	- if current_user.user_voted?(@dare)
		%h4
			You already voted!
	- elsif current_user.is_challenger?(@dare) || current_user.is_acceptor?(@dare)
		%h4
			You can't vote in challenges you are a part of, sorry!
	- else
		= form_for @vote, :url => challenge_dare_votes_path(params[:challenge_id], @dare.id) do |f|
			= f.label :vote_for
			= f.select :vote_for, [['For', true], ['Against', false]]
			= f.submit "Vote!", class: "btn btn-success"
- else
	Sign in to vote!

app/views/dares/_voting_result.html.haml
%h3
	This challenge was put to the vote on #{@dare.voting_start_date}

%h4
	Voters decided that  

	- if @dare.won_voting?
		#{@dare.acceptor.username} accomplished the challenge.
	- else
		#{@dare.acceptor.username} failed.

app/views/dares/new.html.haml
.text-center
  %h1
    Who do you want to challenge to 
  %h1.text-danger
    = @challenge.name
    ?

- if @dare.errors.any?
  %h2
    = "There was a problem:"
    %ul
      - @dare.errors.full_messages.each do |msg|
        %li= msg

#select_acceptor.panel-group
  / .panel.panel-default
  /   .panel-heading
  /     %h4.panel-title
  /       %a{"data-parent" => "#select_acceptor", "data-toggle" => "collapse", :href => "#friends"}
  /         Friends
  /   #friends.panel-collapse.collapse.in.select_user
  /     .panel-body
  /       Coming soon!
  .panel.panel-default
    .panel-heading
      %h4.panel-title
        %a{"data-parent" => "#select_acceptor", "data-toggle" => "collapse", :href => "#ranking"}
          Ranking
    #ranking.panel-collapse.collapse.select_user
      .panel-body
        = render 'users/ranking'
  .panel.panel-default
    .panel-heading
      %h4.panel-title
        %a{"data-parent" => "#select_acceptor", "data-toggle" => "collapse", :href => "#search_box"}
          Find by name/email
    #search_box.panel-collapse.collapse.select_user
      .panel-body
        = render 'users/search_box'
  .panel.panel-default
    .panel-heading
      %h4.panel-title
        %a{"data-parent" => "#select_acceptor", "data-toggle" => "collapse", :href => "#invite"}
          Invite your friends
    #invite.panel-collapse.collapse.select_user
      .panel-body
        .col-md-6
          = render 'users/invite'

#user_search_result

app/views/dares/show.html.haml
- if @dare.errors.any?
  #error_explanation
    = render 'errors'

- if @dare.acceptor_id == @dare.challenger_id
  %h3    
    #{@dare.challenger.username} has challenged himself to #{@dare.challenge.name} challenge!
-else
  %h3
    #{@dare.challenger.username} has challenged #{@dare.acceptor.username} to #{@dare.challenge.name} challenge!

- if @dare.rejected?
  %h2
    #{@dare.acceptor.username} has rejected the challenge:(

- else
  Started on:
  = @dare.created_at
  
  %p
    Status:
    = @dare.status
  - if @dare.times_up?
    Time for finishing this challenge has ended on
  - elsif @dare.resolved?   
    %h4
      This challenged has already finished
  - elsif @dare.voting_in_progress?
    %h4
      We are not sure whether the challenge has been accomplished, help us decide whether the proof uploaded is valid
  - else
    %br
    Finishing in:
    %time{"data-livestamp" => (@dare.created_at + 7.days).to_i}


  - if @dare.status == 'Success'
    %h4
      #{@dare.acceptor.username} has successfully accomplished the #{@dare.challenge.name} challenge!

  - elsif user_signed_in? && current_user.is_acceptor?(@dare) && @dare.still_have_time? && @dare.unresolved?
    = render 'upload_proof'
  %br
  = render 'display_proof'
  


  - if @dare.voting_in_progress?
    = render 'voting'

  - if @dare.after_voting?
    = render 'voting_result'

app/views/dares/show_invitation_dare.html.haml
%h1
  This is an Invitation Challenge
%h3#new-user-email{"data-email" => "#{@dare.invitation.recipient_email}" }
  Recipient: #{@dare.invitation.recipient_email}

%h3 
  Challenger: #{@dare.challenger.username}
%h4
  = @dare.challenge.description



- if user_signed_in?
  = link_to accept_challenge_challenge_dare_path(@dare.challenge_id, @dare.id), method: :put do
    %button.btn.btn-success Accept
  = link_to reject_challenge_challenge_dare_path(@dare.challenge_id, @dare.id), method: :put do
    %button.btn.btn-danger Reject
- else
  = link_to invitation_register_path(@dare.invitation.token) do
    %button.btn.btn-success Accept
  = link_to invitation_register_path(@dare.invitation.token) do
    %button.btn.btn-danger Reject

app/views/dares/show_voting.html.haml
%h1
	These need your vote!

- @dares_voting.each do |dare|
	%h3
		= link_to "#{dare.acceptor.username}'s #{dare.challenge.name}", challenge_dare_path(dare.challenge, dare)