config/routes.rb
Rails.application.routes.draw do

get 'challenges/:challenge_id/dares/:id/:token' => 'dares#show_invitation_dare', as: 'invitation_dare'

devise_scope :user do
  get "/users/sign_up/:token" => "devise/registrations#new", as: 'invitation_register'
end

resources :invitations, only: [:create, :new]

  resources :challenges do
    resources :dares do
      member do
        put 'accept_challenge'
        put 'reject_challenge'
      end
      resources :votes
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations"}

  get 'users/search' => 'users#search'
  get 'users/autocomplete' => 'users#autocomplete'
  get 'users/:id' => 'users#show', as: 'user'
  get 'users' => 'users#index', as: 'users'
  get 'dares_voting' => 'dares#show_voting', as: 'dares_voting'
  get 'notifications' => 'notifications#index'
  put 'challenges/:challenge_id/dares/:id/delete_proof/:proof_type/:proof_id' => 'dares#delete_proof', as: 'delete_proof'
  put 'challenges/:challenge_id/dares/:id/accept_proof' =>  'dares#accept_proof', as: 'accept_proof'
  put 'challenges/:challenge_id/dares/:id/reject_proof' =>  'dares#reject_proof', as: 'reject_proof'
  

  get '/' => 'challenges#intro', as: 'intro'
  root 'challenges#intro'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :dares, foreign_key: :challenger_id
  has_many :accepted_dares, class_name: "Dare", foreign_key: :acceptor_id
  has_many :challenges, through: :dares
  has_many :votes

  has_many :sent_invitations, :class_name => 'Invitation', :foreign_key => 'user_id'
  belongs_to :invitation

  validates :username, presence: true, uniqueness: true, length: { in: 2..50 }

  after_create :set_can_post_on_fb
  after_create :send_welcome_email
  # after_create :post_joined_challenger
  


  include PgSearch
  pg_search_scope :search, against: [:username, :email],
  using: {tsearch: {prefix: true, dictionary: "english" }}

  attr_accessor :login

  def set_can_post_on_fb
    if self.provider == "facebook"
      permissions = self.facebook.get_connection("me", "permissions")
      if permissions.include? ({"permission"=>"publish_actions", "status"=>"granted"})
        self.can_post = true
        save!
      end
    end
  end

  def can_post_on_fb?
    self.can_post == true
  end


  def post_joined_challenger
    if self.provider == "facebook" && self.can_post == true
      self.facebook.put_connections("me", "feed", :message => "Today, I joined the Challenger. It's uber cool. Check it out at simon-challenger.herokuapp.com")
    end
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver
    if self.provider == "facebook" && self.can_post == true
      attachment = {"name"=>"Challenger", "link"=> "simon-challenger.herokuapp.com", "description"=>"Check it out!"}
      self.facebook.put_wall_post("Today, I joined the Challenger. It's uber cool!", attachment) 
   end
  end

  def self.text_search(query)
    if query.present?
      search(query)
    else
      where(nil)
    end
  end

  def friends_counter
    facebook.get_connection("me", "friends").count
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
    block_given? ? yield(@facebook) : @facebook
  rescue Koala::Facebook::AuthenticationError
    logger.info e.to_s
    nil
  end

  def self.from_omniauth(auth)
    oauth = Koala::Facebook::OAuth.new(ENV["fb_app_id"], ENV["fb_app_secret"])
    new_access_info = oauth.exchange_access_token_info auth.credentials.token

    new_access_token = new_access_info["access_token"]
    new_access_expires_at = DateTime.now + new_access_info["expires"].to_i.seconds

    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      user.oauth_token = new_access_token
      user.oauth_expires_at = new_access_expires_at
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def password_required?
    super && self.provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def has_no_password?
    self.encrypted_password.blank?
  end

  def is_acceptor?(dare)
    self.accepted_dares.where('id = ?', dare.id).present?
  end

  def is_challenger?(dare)
    self.dares.where('id = ?', dare.id).present?
  end

  def my_pending_challenges
    self.accepted_dares.where("status = ?", 'Pending')
  end

  def my_challenged_users
    self.dares.where.not(acceptor_id: self.id)
  end

  def challenges_ending_tomorrow
    self.accepted_dares.where(["start_date <= ? and status = ?", 6.days.ago, "Accepted"])
  end

  def already_accepted_this_challenge?(challenge)
    self.accepted_dares.where("challenge_id = ?", challenge.id).exists?
  end

  def my_pending_challenges
    self.accepted_dares.where("status = ?", 'Pending')
  end

  def my_accepted_challenges
    self.accepted_dares.where("status = ?", 'Accepted')
  end

  def completed_challanges
    self.accepted_dares.where("status = ? OR status = ?", "Success", "Voting-Success")
  end

  def failed_challenges
    self.accepted_dares.where("status = ?", 'Failed')
  end

  def rejected_challenges
    self.accepted_dares.where("status = ?", 'Rejected')
  end

  def user_voted?(dare)
    self.votes.where("dare_id = ?", dare.id).any?
  end

  def self.sorted_by_accepted_dares
    self.joins(:accepted_dares).select("count(dares.*) as dare_count, users.*").where("dares.status = ?","Success").group("users.id").order("dare_count DESC")
  end

  def self.sorted_by_least_success
    self.joins(:accepted_dares).select("count(dares.*) as least_success_dare_count, users.*").where("dares.status = ?","Success").group("users.id").order("least_success_dare_count ASC")
  end

  def self.sorted_by_failed_accepted_dares
    self.joins(:accepted_dares).select("count(dares.*) as failed_dare_count, users.*").where("dares.status = ?","Failed").group("users.id").order("failed_dare_count DESC")
  end

  def self.no_success
    self.joins(:accepted_dares).select("count(dares.*) as no_success_dare_count, users.*").where("dares.status != ?","Success").group("users.id").order("no_success_dare_count DESC")
  end

  def first_log_in?
    self.sign_in_count == 1
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  respond_to :js

  def index
    @users = User.sorted_by_accepted_dares
  end

  def autocomplete
    @users = User.order("username, email").where("username ILIKE ? OR email ILIKE ?", "%#{params[:term]}%", "%#{params[:term]}%")
    render json: @users.map(&:username)
  end

  def search
    @users = User.text_search(params[:query])
    @dare = Dare.new
    @challenge = Challenge.find(params[:challenge])
  end

  
  def show
    @user=User.find(params[:id])
    @challenged_users = @user.dares.where.not(acceptor_id: @user.id)
  end

  

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_challenge_user.html.haml
= form_for([@challenge, @dare]) do |f|
	- @dare.challenger_id = current_user.id
	- @dare.challenge_id = @challenge.id
	- @dare.acceptor_id = user.id

	= f.hidden_field :challenger_id
	= f.hidden_field :challenge_id
	= f.hidden_field :acceptor_id
	= f.submit "Challenge!", class: 'btn btn-md btn-danger'

app/views/users/_challenged_users.html.haml
- current_user.my_challenged_users.each do |i|
	%p
		= link_to i.acceptor.username
		to 
		= link_to "#{i.challenge.name},", i.challenge
		finishes 
		%time{"data-livestamp" => (i.created_at + 7.days).to_i}

app/views/users/_find_user.html.haml
- if @users.empty?	
  %h4
    Sorry, we ain't have nobody like that
- else
  .table-responsive
  %table.table#user-search-table
    %thead
      %tr
        %th
          User
        %th
          %span.glyphicon.glyphicon-thumbs-up
        %th
          %span.glyphicon.glyphicon-thumbs-down
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td
            = user.username
          %td
            = user.completed_challanges.count
          %td
            = user.failed_challenges.count
          %td.pull-right
            = render partial: 'users/challenge_user', locals: {:user => user}

app/views/users/_invite.html.haml
= simple_form_for @invitation do |f|
  - if @invitation.errors.any?
    #error_explanation
      = render 'errors'
  - @invitation.challenge_id = @dare.challenge_id
  = f.hidden_field :challenge_id
  = f.input :recipient_email, required: false, input_html: {class: 'width-100'}
  = f.button :submit

app/views/users/_most_failed.html.haml
- User.sorted_by_failed_accepted_dares.each do |user|
	%h5
		= link_to user.username, user_path(user)
		has failed
		= pluralize user.failed_dare_count, 'challenge'
		= render partial: 'users/challenge_user', locals: {:user => user}

app/views/users/_most_success.html.haml
- User.sorted_by_accepted_dares.each do |user|
	%h5
		= link_to user.username, user_path(user)
		has completed
		= pluralize user.dare_count, 'challenge'
		= render partial: 'users/challenge_user', locals: {:user => user}

app/views/users/_ranking.html.haml
.table-responsive
  %table.table#user-ranking
    %thead
      %tr
        %th
          User
        %th
          %span.glyphicon.glyphicon-thumbs-up
        %th
          %span.glyphicon.glyphicon-thumbs-down
        %th
    %tbody
      - User.all.each do |user|
        %tr
          %td
            = user.username
          %td
            = user.completed_challanges.count
          %td
            = user.failed_challenges.count
          %td
            = form_for([@challenge, @dare]) do |f|
              - @dare.challenger_id = current_user.id
              - @dare.challenge_id = @challenge.id
              - @dare.acceptor_id = user.id

              = f.hidden_field :challenger_id
              = f.hidden_field :challenge_id
              = f.hidden_field :acceptor_id
              = f.submit "&#x2713;".html_safe

app/views/users/_search.html.haml
- unless @users.nil?	
	- @users.each do |user|
		%h3	
			= link_to user.username, user_path(user)
			has completed
			= pluralize user.accepted_dares.where('status = ?', 'Success').count, 'challenge'
		= link_to challenges_path  do
			%button.btn.btn-lg.btn-info Challenge!

app/views/users/_search_box.html.haml
= form_tag users_search_path, method: :get, remote: true do 
	%p
		= hidden_field_tag 'challenge', params[:challenge_id]
		= text_field_tag :query, params[:query], data: {autocomplete_source: users_autocomplete_path}
		= submit_tag "Search", name: nil, id: 'search_for_users'

app/views/users/_user_info.html.haml
%p
	= link_to current_user.username, current_user
%p
	= link_to 'Edit account', edit_user_registration_path
%p
	= link_to 'Sign out', destroy_user_session_path, :method=>'delete'

app/views/users/_user_notifications.html.haml
#notifications{name:'notifications'}
	- current_user.my_pending_challenges.each do |dare|
		%p
			You have been challenged by 
			= link_to dare.challenger.username, dare.challenger
			to accept
			= link_to dare.challenge.name, challenge_dare_path(dare.challenge, dare)
		= render partial: 'shared/accept_reject_challenge', locals: {:dare => dare}

	- current_user.challenges_ending_tomorrow.each do |c|
		%p
			Your time to finish
			= link_to c.challenge.name, challenge_dare_path(c.challenge, c)
			is ending in
			- if c.start_date
				= c.finishing_in
				days

app/views/users/index.html.haml
%h1
	Challenge aficionados

- @users.each do |user|
	%h3	
		= link_to user.username, user_path(user)
		has completed
		= pluralize user.dare_count, 'challenge'

app/views/users/search.js.erb
$('#user_search_result').html("<%= j (render 'users/find_user') %>");
$('#user-search-table').dataTable();
$('#user-search-table_filter').hide();

app/views/users/show.html.haml
%h2= @user.username
%h3= @user.email

%h4
	= @user.username 
	has accepted:
	= pluralize @user.accepted_dares.count, 'challenge'

- @user.accepted_dares.each do |dare|
	%p
		= link_to dare.challenge.name, challenge_dare_path(challenge_id: dare.challenge.id, id: dare.id)


%h4 
	= @user.username 
	has challenged:
	= pluralize @challenged_users.count, 'user'

- @challenged_users.each do |i|
	%p
		= link_to i.acceptor.username, i.acceptor

%h4
	= @user.username 
	has completed:
	= pluralize @user.completed_challanges.count, 'challenge'

- @user.completed_challanges.each do |completed_challenge|
	%p
		= link_to completed_challenge.challenge.name, challenge_dare_path(challenge_id: completed_challenge.challenge.id, id: completed_challenge.id)

%h4
	= @user.username 
	has failed at:
	= pluralize @user.failed_challenges.count, 'challenge'

- @user.failed_challenges.each do |failed_challenge|
	%p
		= link_to failed_challenge.challenge.name, user_path(failed_challenge)

%h4
	= @user.username 
	has rejected:
	= pluralize @user.rejected_challenges.count, 'challenge'

- @user.rejected_challenges.each do |rejected_challenge|
	%p
		= link_to rejected_challenge.challenge.name, rejected_challenge.challenge