config/routes.rb
Rails.application.routes.draw do

get 'challenges/:challenge_id/dares/:id/:token' => 'dares#show_invitation_dare', as: 'invitation_dare'

devise_scope :user do
  get "/users/sign_up/:token" => "devise/registrations#new", as: 'invitation_register'
end

resources :invitations, only: [:create, :new]

  resources :challenges do
    resources :dares do
      member do
        put 'accept_challenge'
        put 'reject_challenge'
      end
      resources :votes
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations"}

  get 'users/search' => 'users#search'
  get 'users/autocomplete' => 'users#autocomplete'
  get 'users/:id' => 'users#show', as: 'user'
  get 'users' => 'users#index', as: 'users'
  get 'dares_voting' => 'dares#show_voting', as: 'dares_voting'
  get 'notifications' => 'notifications#index'
  put 'challenges/:challenge_id/dares/:id/delete_proof/:proof_type/:proof_id' => 'dares#delete_proof', as: 'delete_proof'
  put 'challenges/:challenge_id/dares/:id/accept_proof' =>  'dares#accept_proof', as: 'accept_proof'
  put 'challenges/:challenge_id/dares/:id/reject_proof' =>  'dares#reject_proof', as: 'reject_proof'
  

  get '/' => 'challenges#intro', as: 'intro'
  root 'challenges#intro'

end

app/views/shared/_accept_reject_challenge.html.haml
/ = form_for([dare.challenge, dare]) do |f|
/ 	- dare.status = "Accepted"
/ 	- dare.start_date = DateTime.now
/ 	= f.hidden_field :status
/ 	= f.hidden_field :start_date
/ 	= f.submit "Accept", class: "btn btn-primary"
/ 	= form_for([dare.challenge, dare]) do |f|
/ 		- dare.status = "Rejected"
/ 		- dare.end_date = DateTime.now
/ 		= f.hidden_field :status
/ 		= f.hidden_field :end_date
/ 		= f.submit "Reject", class: "btn btn-danger"
= link_to accept_challenge_challenge_dare_path(dare.challenge_id, dare.id), method: :put do
	%button.btn.btn-success Accept
= link_to reject_challenge_challenge_dare_path(dare.challenge_id, dare.id), method: :put do
	%button.btn.btn-danger Reject

app/views/shared/_accordion.html.haml
- if user_signed_in?
  #accordion.panel-group
    .panel.panel-default
      .panel-heading
        %h4.panel-title
          %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseOne"}
            Notifications:
            %span#pending-notifications= current_user.my_pending_challenges.count if current_user.my_pending_challenges.any?

      #collapseOne.panel-collapse.collapse.in.panel-body.user_panel
        = render 'users/user_notifications'
    .panel.panel-default
      .panel-heading
        %h4.panel-title
          %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseTwo"}
            Accepted Challenges:
      #collapseTwo.panel-collapse.in.collapse
        .panel-body.user_panel#accepted_challenges
          = render 'challenges/accepted_challenges' 
    .panel.panel-default
      .panel-heading
        %h4.panel-title
          %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseThree"}
            You have challenged:
      #collapseThree.panel-collapse.in.collapse
        #i_challenged.panel-body.user_panel
          = render 'challenges/i_challenged'
    .panel.panel-default
      .panel-heading
        %h4.panel-title
          %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseFour"}
            Recently put to the vote:
      #collapseFour.panel-collapse.in.collapse
        .panel-body.user_panel
          = render 'shared/newest_voting'
  = link_to new_challenge_path do
    %button.btn.btn-lg.btn-info New Challenge


 

app/views/shared/_intro.html.haml
.text-center
	%h2
		Bored with the monotony of you everyday life? 
	%h3
		Challenger to the rescue!!! 
	%h3
		Accept a challenge, challenge your friends, do something you would be proud of...
		 
	- if user_signed_in?
		%h3
			= link_to 'Choose your destiny!', challenges_path
	- else
		%h3
			Log in with your 	
			= link_to user_omniauth_authorize_path(:facebook), id: 'sign_in' do
				%button.btn.btn-md.btn-primary Facebook
			or
			= link_to  new_user_registration_path do
				%button.btn.btn-md.btn-success Email
			account and make it rain!

app/views/shared/_newest_voting.html.haml
-  Dare.newest_voting.each do |dare|
	%p
		= link_to dare.challenge.name, challenge_dare_path(dare.challenge, dare) 
		was put to the vote
	

app/views/shared/_user_login.html.haml
- if user_signed_in?
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      = current_user.username
      %span.caret
    %ul.dropdown-menu{:role => "menu"}
      %li
        = link_to 'Profile', current_user
      %li
        = link_to 'Edit account', edit_user_registration_path
      %li.divider
      %li
        = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  = link_to user_omniauth_authorize_path(:facebook), id: 'sign_in_fb' do
    %button.btn.btn-md.btn-primary Facebook Connect
  = link_to new_user_session_path do
    %button.btn.btn-sm.btn-default Sign in
  = link_to new_user_registration_path do
    %button.btn.btn-sm.btn-default Sign up