config/routes.rb
Rails.application.routes.draw do

get 'challenges/:challenge_id/dares/:id/:token' => 'dares#show_invitation_dare', as: 'invitation_dare'

devise_scope :user do
  get "/users/sign_up/:token" => "devise/registrations#new", as: 'invitation_register'
end

resources :invitations, only: [:create, :new]

  resources :challenges do
    resources :dares do
      member do
        put 'accept_challenge'
        put 'reject_challenge'
      end
      resources :votes
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations"}

  get 'users/search' => 'users#search'
  get 'users/autocomplete' => 'users#autocomplete'
  get 'users/:id' => 'users#show', as: 'user'
  get 'users' => 'users#index', as: 'users'
  get 'dares_voting' => 'dares#show_voting', as: 'dares_voting'
  get 'notifications' => 'notifications#index'
  put 'challenges/:challenge_id/dares/:id/delete_proof/:proof_type/:proof_id' => 'dares#delete_proof', as: 'delete_proof'
  put 'challenges/:challenge_id/dares/:id/accept_proof' =>  'dares#accept_proof', as: 'accept_proof'
  put 'challenges/:challenge_id/dares/:id/reject_proof' =>  'dares#reject_proof', as: 'reject_proof'
  

  get '/' => 'challenges#intro', as: 'intro'
  root 'challenges#intro'

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  
  has_many :dares
  has_many :users, through: :dares, source: :challenges

  validates :name, presence: true, uniqueness: true, length: { in: 5..100 }
  validates :description, presence: true, length: { in: 10..500 }

  include PgSearch
  pg_search_scope :search, against: [:name, :description],
                  using: {tsearch: {prefix: true, dictionary: "english" }}

  # after_save :create_dare

  def self.text_search(query)
    if query.present?
      search(query)
    else
      where(nil)
    end
  end

  def self.newest
    order(:created_at)
  end

  def self.sort_by_name
    order(:name)
  end

  def self.sort(choice)
    order(choice)
  end

  def rejected_by
    self.dares.where("status = ?", 'Rejected')
  end

  def accepted_by
    self.dares.where("status = ?", 'Accepted')
  end  

  def completed_by
    self.dares.where("status = ?", 'Completed')
  end 
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, except: [:index,:new, :create, :popular_challenges, :intro]
  respond_to :js

  def intro
  end

  def index
    @challenges = Challenge.text_search(params[:query])

    if params[:choice]
      direction = params[:choice].end_with?("1") ? "ASC" : "DESC"
    end

    @sorted_challenges = case params[:choice]
    when "popular", "popular1"
      Challenge.order("dares_count #{direction}")
    when "date", "date1"
      Challenge.order("created_at #{direction}")
    when "name", "name1"
      Challenge.order("name #{direction}")
    end
  end

  def show
  end

  def new
    @challenge = Challenge.new
  end

  def edit
  end

  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.js 
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

  def set_challenge
    @challenge = Challenge.find(params[:id])
  end


  def challenge_params
    params.require(:challenge).permit(:user_id, :name, :description)
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_about_fb.html.haml
#about-fb-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        %h3#myModalLabel.modal-title
          About Facebook Posts
      .modal-body
        %h4
          Thank you for allowing Challenger to post on your Facebook wall.
        %h4
          By default, we will post when you:
          %ul{:style => "list-style-type:disc"}
            %li accept a challenge
            %li upload proof
            %li your challenge is put to the vote
            %li the voting for your challenge ends
          You can disable the posting in your
          = link_to 'account settings', edit_user_registration_path

app/views/challenges/_errors.html.haml
%h4
  = "#{pluralize(@challenge.errors.count, "error")} prohibited this challenge from being saved:"
  %ul
    - @challenge.errors.full_messages.each do |msg|
      %li= msg

app/views/challenges/_form.html.haml
= form_for @challenge do |f|
  - if @challenge.errors.any?
    #error_explanation
      = render 'errors'

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/challenges/_i_challenged.html.haml
- current_user.my_challenged_users.each do |dare|
	%p
		= link_to dare.acceptor.username, dare.acceptor
		to 
		= link_to "#{dare.challenge.name},", challenge_dare_path(dare.challenge, dare)
		finishes 
		%time{"data-livestamp" => (dare.created_at + 7.days).to_i}

app/views/challenges/_user.html.haml
-User.all.each do |user|
 = link_to user.username

app/views/challenges/challenge_others.html.haml
%h2 Who do you want to challenge to complete @challenge?
= @challenge.name

app/views/challenges/create.js.erb
<% if @challenge.errors.messages.blank? %>
	$('#challenges').append("<%= j(render @challenge) %>");
	$('#errors').html("<h3>Created new challenge - <%= j(@challenge.name) %></h3>");
<% else %>
	$('#errors').html("<%= j(render 'errors') %>");
<% end %>

app/views/challenges/index.html.haml
Sort by:
= link_to 'Name', challenges_path(choice: 'name'), remote: true, class: 'sort_link'
%span.sort-arrow-up.hidden &#x25B2
%span.sort-arrow-down &#x25BC
= link_to 'Added on', challenges_path(choice: "date"), remote: true, class: 'sort_link horizontal-break'
%span.sort-arrow-up.hidden &#x25B2
%span.sort-arrow-down &#x25BC
= link_to 'Popular', challenges_path(choice: "popular"), remote: true, class: 'sort_link horizontal-break'
%span.sort-arrow-up.hidden &#x25B2
%span.sort-arrow-down &#x25BC


%h1 Listing challenges

#challenges
  = render @challenges
%br
#errors
#new-challenge-form

app/views/challenges/index.js.erb
$('#challenges').html("<%= j(render @sorted_challenges) %>").addClass('animated rubberBand');

app/views/challenges/intro.html.haml
= render 'shared/intro'

app/views/challenges/new.html.haml
%h1 New challenge

= render 'form'

= link_to 'Back', challenges_path

app/views/challenges/new.js.erb
$('#new-challenge-form').html("<%= j(render 'form') %>");

app/views/challenges/select_user.html.haml
%h2 Who do you want to challenge to  #{@challenge.name}?
- User.all.each do |user|
	= link_to user.username, challenge_dares_path(@challenge, :user => user), :method => :post

app/views/challenges/show.html.haml
%p#notice= notice

%p
  %b Completed by:
  = pluralize @challenge.completed_by.count, 'user'
  - @challenge.completed_by.each do |i|
    = link_to i.acceptor.username, i.acceptor

%p
  %b Accepted by:
  = pluralize @challenge.accepted_by.count, 'user'
  - @challenge.accepted_by.each do |i|
    = link_to i.acceptor.username, i.acceptor

%p
  %b Rejected by:
  = pluralize @challenge.rejected_by.count, 'user'
  - @challenge.rejected_by.each do |i|
    = link_to i.acceptor.username, i.acceptor

%p
  %b Name:
  = @challenge.name
%p
  %b Description:
  = @challenge.description


%h5.display-inline
  Invite you friend to try out this challenge!

.fb-send{"data-colorscheme" => "light", "data-href" => "http://simon-challenger.herokuapp.com/challenges/#{@challenge.id}"}

/ %button.btn.btn-md.btn-danger#fb_post Post on FB 

.control-buttons
  = link_to 'Edit', edit_challenge_path(@challenge)
  \|
  = link_to 'Back', challenges_path